name: accessibility-testing

on: [push, pull_request]

jobs:
    accessibility:
        permissions:
          contents: read
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install Python 3.9
          uses: actions/setup-python@v5
          with: 
            python-version: "3.9"
        - name: Install node
          uses: actions/setup-node@v4
          with:
            node-version: '22'
        - name: Install python dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
        - name: Install node dependencies
          run: |
            npm install jest jest-environment-node puppeteer pa11y
            npx puppeteer browsers install chrome
        - name: Setup app and run tests
          run: |
            source venv/bin/activate
            flask --debug setup ../tests_python/test_configurations/config-equal-item-weights.json
            flask --debug run --host=0.0.0.0 --port=5001 & sleep 5
            npx jest -- tests_accessibility
